export const REMAINING_BATCH_01_GROUP_4_APPROVAL_QUOTE =
  '족발은 "발을 먹는데? 손이 더 바쁘다" 에서 "더"가 빠졌어 중요한 요소야 수정해줘.  나머지는 다 맘에 들어'

export const REMAINING_BATCH_01_GROUP_4_SOURCE_MANIFEST = Object.freeze({
  path: 'tmp/narration-preview/remaining-batch-01/remaining-batch-01-manifest.json',
  byteLength: 42_007,
  sha256:
    'C2A6A2846C37A76C1FCF4A8E7F1E7F6255248D007D0712288EC934736CBF107E',
  schemaVersion: 2,
  generatedAt: '2026-08-10T04:18:00.701Z',
  region: 'southeastasia',
  outputFormat: 'audio-24khz-160kbitrate-mono-mp3',
  totalSynthesisRequests: 28,
  retries: 0,
  postprocessingApplied: false,
})

const approved = (selection) =>
  Object.freeze({
    ...selection,
    sourceManifest: REMAINING_BATCH_01_GROUP_4_SOURCE_MANIFEST,
    approvalEvidence: Object.freeze({
      userStatement: REMAINING_BATCH_01_GROUP_4_APPROVAL_QUOTE,
      reviewedAt: '2026-08-10',
    }),
    humanApproved: true,
    approvalState: 'unconditional-raw-take-approved',
    deploymentStatus: 'active',
    currentlyDeployed: true,
    byteCopyVerified: true,
    postprocessingApplied: false,
    additionalAzureRequests: 0,
  })

export const REMAINING_BATCH_01_GROUP_4_APPROVED_NARRATION_SELECTIONS =
  Object.freeze([
    approved({
      menuId: 'dakgalbi',
      tone: 'deadpan',
      catalogText: '닭은 있는데 갈비는 어디 갔지?',
      spokenText: '닭은 있는데 갈비는 어디 갔지?',
      sourcePreviewPath: 'tmp/narration-preview/remaining-batch-01/dakgalbi.mp3',
      targetAssetPath:
        'src/assets/narration/dakgalbi-remaining-batch-01.mp3',
      byteLength: 36_960,
      sha256:
        '2F196CF507647193E0A71C8E1949249769D87EBD1372D1EEEB4C28024656201F',
      mpegFrameCount: 77,
      exactDurationSeconds: 1.848,
      modelId: 'mai-voice-2',
      model: 'MAI-Voice-2',
      voiceId: 'junho',
      voiceShortName: 'ko-KR-Junho:MAI-Voice-2',
      style: 'joyful',
      styleDegree: 0.44,
      rate: '+20%',
      pitch: '-1%',
      structure: 'one-block',
      segments: Object.freeze(['닭은 있는데 갈비는 어디 갔지?']),
    }),
    approved({
      menuId: 'bossam',
      tone: 'deadpan',
      catalogText: '배추가 고기를 보쌈했다!',
      spokenText: '배추가 고기를 보쌈했다!',
      sourcePreviewPath: 'tmp/narration-preview/remaining-batch-01/bossam.mp3',
      targetAssetPath: 'src/assets/narration/bossam-remaining-batch-01.mp3',
      byteLength: 48_480,
      sha256:
        'B081A8348CA13C6A9B36DA3D8A8EF595AF674F37ED835AE58CB99BE2F336A26A',
      mpegFrameCount: 101,
      exactDurationSeconds: 2.424,
      modelId: 'flash',
      model: 'MAI-Voice-2-Flash',
      voiceId: 'junho',
      voiceShortName: 'ko-KR-Junho:MAI-Voice-2-Flash',
      style: 'determined',
      styleDegree: 0.46,
      rate: '+20%',
      pitch: '-1%',
      structure: 'one-block',
      segments: Object.freeze(['배추가 고기를 보쌈했다!']),
    }),
    approved({
      menuId: 'bulgogi',
      tone: 'alert',
      catalogText: '엄마 물고기 말고 불고기!',
      spokenText: '엄마 물고기 말고 불고기!',
      sourcePreviewPath: 'tmp/narration-preview/remaining-batch-01/bulgogi.mp3',
      targetAssetPath: 'src/assets/narration/bulgogi-remaining-batch-01.mp3',
      byteLength: 42_720,
      sha256:
        '3E396073B5888176DE9BF942C9093E2C43CB5106F2CA9F78A1DC77AB010B4922',
      mpegFrameCount: 89,
      exactDurationSeconds: 2.136,
      modelId: 'flash',
      model: 'MAI-Voice-2-Flash',
      voiceId: 'junho',
      voiceShortName: 'ko-KR-Junho:MAI-Voice-2-Flash',
      style: 'joyful',
      styleDegree: 0.48,
      rate: '+20%',
      pitch: '-1%',
      structure: 'adjacent-two-block',
      segments: Object.freeze(['엄마', ' 물고기 말고 불고기!']),
    }),
    approved({
      menuId: 'fried-chicken',
      tone: 'epic',
      catalogText: '반반은 우유부단이 아니라 지혜다!',
      spokenText: '반반은 우유부단이 아니라 지혜다!',
      sourcePreviewPath:
        'tmp/narration-preview/remaining-batch-01/fried-chicken.mp3',
      targetAssetPath:
        'src/assets/narration/fried-chicken-remaining-batch-01.mp3',
      byteLength: 52_800,
      sha256:
        'F7C65BFB9379E60767012B532A4C4FB91BD303F3F4B467CDDD1DEC46BBC1FAC7',
      mpegFrameCount: 110,
      exactDurationSeconds: 2.64,
      modelId: 'mai-voice-2',
      model: 'MAI-Voice-2',
      voiceId: 'junho',
      voiceShortName: 'ko-KR-Junho:MAI-Voice-2',
      style: 'joyful',
      styleDegree: 0.48,
      rate: '+26%',
      pitch: '-1%',
      structure: 'one-block',
      segments: Object.freeze(['반반은 우유부단이 아니라 지혜다!']),
    }),
    approved({
      menuId: 'pizza',
      tone: 'alert',
      catalogText: '피자 먹고 팔자 피자!',
      spokenText: '피자 먹고 팔자 피자!',
      sourcePreviewPath: 'tmp/narration-preview/remaining-batch-01/pizza.mp3',
      targetAssetPath: 'src/assets/narration/pizza-remaining-batch-01.mp3',
      byteLength: 43_200,
      sha256:
        '22995289B0EAA4F3902520000CA6E4D8D4A8F42A1E09099B918986A1197EB671',
      mpegFrameCount: 90,
      exactDurationSeconds: 2.16,
      modelId: 'flash',
      model: 'MAI-Voice-2-Flash',
      voiceId: 'junho',
      voiceShortName: 'ko-KR-Junho:MAI-Voice-2-Flash',
      style: 'joyful',
      styleDegree: 0.46,
      rate: '+18%',
      pitch: '+0%',
      structure: 'adjacent-two-block',
      segments: Object.freeze(['피자 먹고', ' 팔자 피자!']),
    }),
    approved({
      menuId: 'dak-hanmari',
      tone: 'deadpan',
      catalogText: '메뉴 이름이 설명서다!',
      spokenText: '메뉴 이름이 설명서다!',
      sourcePreviewPath:
        'tmp/narration-preview/remaining-batch-01/dak-hanmari.mp3',
      targetAssetPath:
        'src/assets/narration/dak-hanmari-remaining-batch-01.mp3',
      byteLength: 40_800,
      sha256:
        'E87B251F72191AD9841E984DA0A2D16E23C5D17AD70E95AF9AF8C13DF7C4C2EC',
      mpegFrameCount: 85,
      exactDurationSeconds: 2.04,
      modelId: 'flash',
      model: 'MAI-Voice-2-Flash',
      voiceId: 'junho',
      voiceShortName: 'ko-KR-Junho:MAI-Voice-2-Flash',
      style: 'determined',
      styleDegree: 0.46,
      rate: '+18%',
      pitch: '-1%',
      structure: 'one-block',
      segments: Object.freeze(['메뉴 이름이 설명서다!']),
    }),
  ])

export const REMAINING_BATCH_01_GROUP_4_WITHHELD_JOKBAL_SELECTION =
  Object.freeze({
    menuId: 'jokbal',
    oldCatalogText: '발을 먹는데 손이 바쁘다!',
    requestedCatalogText: '발을 먹는데? 손이 더 바쁘다!',
    tone: 'playful',
    sourcePreviewPath: 'tmp/narration-preview/remaining-batch-01/jokbal.mp3',
    byteLength: 54_720,
    sha256:
      '9D4505FE633998516A2AABE750920CE2CD14E98709CE87512D67B674D24966BD',
    mpegFrameCount: 114,
    exactDurationSeconds: 2.736,
    originalPerformance: Object.freeze({
      modelId: 'flash',
      model: 'MAI-Voice-2-Flash',
      voiceShortName: 'ko-KR-Junho:MAI-Voice-2-Flash',
      style: 'joyful',
      styleDegree: 0.48,
      rate: '+22%',
      pitch: '+0%',
      structure: 'adjacent-two-block',
      segments: Object.freeze(['발을 먹는데 ', '손이 바쁘다!']),
    }),
    userFeedback: REMAINING_BATCH_01_GROUP_4_APPROVAL_QUOTE,
    approvalState: 'retake-requested-copy-missing-important-word',
    humanApproved: false,
    deploymentStatus: 'withheld-source-not-integrated',
    currentlyDeployed: false,
    runtimeIntegrationAttempted: false,
  })
