export const REMAINING_BATCH_01_GROUP_2_APPROVAL_QUOTE =
  '칼국수 뺴고 나머지 전부 괜찮아 승인할게. 칼국수는 문구를 바꾸자. "칼은 위협용" 으로 문구 바꿔서 재생성 해줘'

export const REMAINING_BATCH_01_GROUP_2_SOURCE_MANIFEST = Object.freeze({
  path: 'tmp/narration-preview/remaining-batch-01/remaining-batch-01-manifest.json',
  byteLength: 42_007,
  sha256: 'C2A6A2846C37A76C1FCF4A8E7F1E7F6255248D007D0712288EC934736CBF107E',
  schemaVersion: 2,
  generatedAt: '2026-08-10T04:18:00.701Z',
  region: 'southeastasia',
  outputFormat: 'audio-24khz-160kbitrate-mono-mp3',
  totalSynthesisRequests: 28,
  retries: 0,
  postprocessingApplied: false,
})

export const REMAINING_BATCH_01_GROUP_2_APPROVED_NARRATION_SELECTIONS =
  Object.freeze([
    selection({
      menuId: 'janchi-guksu',
      tone: 'playful',
      catalogText: '혼자 먹어도 이름은 잔치!',
      byteLength: 38_400,
      sha256: 'FD194B316E15022D3CB9942EA8C1EAF0DD97E1AC04174A8751ECB06F88B2E6DC',
      mpegFrameCount: 80,
      exactDurationSeconds: 1.92,
      voiceId: 'haena',
      voiceShortName: 'ko-KR-Haena:MAI-Voice-2-Flash',
      style: 'joyful',
      styleDegree: 0.46,
      rate: '+20%',
      pitch: '-1%',
      segments: ['혼자 먹어도 이름은 잔치!'],
    }),
    selection({
      menuId: 'naengmyeon',
      tone: 'epic',
      catalogText: '중요한 건 꺾이지 않는 면발!',
      byteLength: 54_240,
      sha256: 'DC9F1CE16DDEEE109F6F18466FBF3C6A99DD448322599DE6B3EDC3343893F7ED',
      mpegFrameCount: 113,
      exactDurationSeconds: 2.712,
      voiceId: 'junho',
      voiceShortName: 'ko-KR-Junho:MAI-Voice-2-Flash',
      style: 'determined',
      styleDegree: 0.52,
      rate: '+22%',
      pitch: '-1%',
      segments: ['중요한 건 ', '꺾이지 않는 면발!'],
    }),
    selection({
      menuId: 'jjajangmyeon',
      tone: 'alert',
      catalogText: '짜장면 등장, 젓가락 급가속!',
      byteLength: 53_280,
      sha256: 'D0915E8C2EF31A045AFBA3F9EB33B03C324F85746823EC876225437D663043E1',
      mpegFrameCount: 111,
      exactDurationSeconds: 2.664,
      voiceId: 'junho',
      voiceShortName: 'ko-KR-Junho:MAI-Voice-2-Flash',
      style: 'joyful',
      styleDegree: 0.5,
      rate: '+22%',
      pitch: '+0%',
      segments: ['짜장면 등장, ', '젓가락 급가속!'],
    }),
    selection({
      menuId: 'jjamppong',
      tone: 'playful',
      catalogText: '국물 한입, 정신 자동 재부팅!',
      byteLength: 68_640,
      sha256: 'AC9A1604F287BD18AE97B5DF2B28E7BD1923484673D3BB07B9D9A03CCF709E32',
      mpegFrameCount: 143,
      exactDurationSeconds: 3.432,
      voiceId: 'haena',
      voiceShortName: 'ko-KR-Haena:MAI-Voice-2-Flash',
      style: 'joyful',
      styleDegree: 0.48,
      rate: '+22%',
      pitch: '-1%',
      segments: ['국물 한입, ', '정신 자동 재부팅!'],
      durationReview: Object.freeze({
        status: 'human-listening-exception',
        exactDurationSeconds: 3.432,
        userAcceptedRawTake: true,
        trimApplied: false,
      }),
    }),
    selection({
      menuId: 'udon',
      tone: 'deadpan',
      catalogText: '우동은 굵고 고민은 짧다!',
      byteLength: 47_040,
      sha256: '02C218A01E8D4130BDA92E82556A64969D3F195D849F89DC263F0A33DBD80FC4',
      mpegFrameCount: 98,
      exactDurationSeconds: 2.352,
      voiceId: 'junho',
      voiceShortName: 'ko-KR-Junho:MAI-Voice-2-Flash',
      style: 'determined',
      styleDegree: 0.46,
      rate: '+20%',
      pitch: '-1%',
      segments: ['우동은 굵고 ', '고민은 짧다!'],
    }),
    selection({
      menuId: 'pho',
      tone: 'deadpan',
      catalogText: '고수 넣는 자가 진짜 고수!',
      byteLength: 33_120,
      sha256: '5F0AACBE13CF78CDD84D1A483F4240FB05783800E9E4F8CF7D55B4E1F129A7CA',
      mpegFrameCount: 69,
      exactDurationSeconds: 1.656,
      voiceId: 'junho',
      voiceShortName: 'ko-KR-Junho:MAI-Voice-2-Flash',
      style: 'determined',
      styleDegree: 0.48,
      rate: '+20%',
      pitch: '-1%',
      segments: ['고수 넣는 자가 ', '진짜 고수!'],
    }),
  ])

export const REMAINING_BATCH_01_GROUP_2_REJECTED_KALGUKSU = Object.freeze({
  menuId: 'kalguksu',
  rejectedCatalogText: '칼은 이름에만, 국물은 따뜻!',
  rejectedSourcePreviewPath:
    'tmp/narration-preview/remaining-batch-01/kalguksu.mp3',
  rejectedByteLength: 77_760,
  rejectedSha256:
    '5AB16C2DF6ED341A498FA2D00DB3DDC0C90A5EC22968A27918043FED16E3438C',
  rejectedMpegFrameCount: 162,
  rejectedExactDurationSeconds: 3.888,
  replacementCatalogText: '칼은 위협용!',
  userStatement: REMAINING_BATCH_01_GROUP_2_APPROVAL_QUOTE,
  humanApproved: false,
  deploymentStatus: 'rejected-source-not-integrated',
  currentlyDeployed: false,
  runtimeIntegrationAttempted: false,
})

function selection(value) {
  return Object.freeze({
    ...value,
    spokenText: value.catalogText,
    sourcePreviewPath:
      `tmp/narration-preview/remaining-batch-01/${value.menuId}.mp3`,
    targetAssetPath:
      `src/assets/narration/${value.menuId}-remaining-batch-01.mp3`,
    model: 'MAI-Voice-2-Flash',
    structure:
      value.segments.length === 1 ? 'one-block' : 'adjacent-two-block',
    segments: Object.freeze([...value.segments]),
    durationReview:
      value.durationReview ??
      Object.freeze({
        status: 'human-approved-raw-take',
        exactDurationSeconds: value.exactDurationSeconds,
        userAcceptedRawTake: true,
        trimApplied: false,
      }),
    sourceManifest: REMAINING_BATCH_01_GROUP_2_SOURCE_MANIFEST,
    humanApproved: true,
    approvalState: 'unconditional-raw-take-approved',
    approvalEvidence: Object.freeze({
      userStatement: REMAINING_BATCH_01_GROUP_2_APPROVAL_QUOTE,
      reviewedAt: '2026-08-10',
    }),
    deploymentStatus: 'active',
    currentlyDeployed: true,
    byteCopyVerified: true,
    postprocessingApplied: false,
    additionalAzureRequests: 0,
  })
}
