export const REMAINING_BATCH_01_GROUP_3_APPROVAL_QUOTE =
  '떡볶이는 앞에 "떡볶"이가 안들리고 앞부분이 짤린거 같아. 떡볶이는 짤린거 말고는 괜찮아. 햄버거는 햄부기 3번 반복하는데 더 빠르게 반복해줘. 이 둘 말고는 괜찮아'

export const REMAINING_BATCH_01_GROUP_3_SOURCE_MANIFEST = Object.freeze({
  path: 'tmp/narration-preview/remaining-batch-01/remaining-batch-01-manifest.json',
  byteLength: 42_007,
  sha256:
    'C2A6A2846C37A76C1FCF4A8E7F1E7F6255248D007D0712288EC934736CBF107E',
  schemaVersion: 2,
  generatedAt: '2026-08-10T04:18:00.701Z',
  region: 'southeastasia',
  outputFormat: 'audio-24khz-160kbitrate-mono-mp3',
  totalSynthesisRequests: 28,
  retries: 0,
  postprocessingApplied: false,
})

const approved = (selection) =>
  Object.freeze({
    ...selection,
    sourceManifest: REMAINING_BATCH_01_GROUP_3_SOURCE_MANIFEST,
    approvalEvidence: Object.freeze({
      userStatement: REMAINING_BATCH_01_GROUP_3_APPROVAL_QUOTE,
      reviewedAt: '2026-08-10',
    }),
    humanApproved: true,
    approvalState: 'unconditional-raw-take-approved',
    deploymentStatus: 'active',
    currentlyDeployed: true,
    byteCopyVerified: true,
    postprocessingApplied: false,
    additionalAzureRequests: 0,
  })

export const REMAINING_BATCH_01_GROUP_3_APPROVED_NARRATION_SELECTIONS =
  Object.freeze([
    approved({
      menuId: 'gimbap',
      tone: 'deadpan',
      catalogText: '꼬다리 소유권 분쟁 발생!',
      spokenText: '꼬다리 소유권 분쟁 발생!',
      sourcePreviewPath: 'tmp/narration-preview/remaining-batch-01/gimbap.mp3',
      targetAssetPath: 'src/assets/narration/gimbap-remaining-batch-01.mp3',
      byteLength: 40_320,
      sha256:
        '3D1948080A77B27876D9DF1BFB7F96A7A3D2746E9117037163B8A7BFCF69497D',
      mpegFrameCount: 84,
      exactDurationSeconds: 2.016,
      modelId: 'flash',
      model: 'MAI-Voice-2-Flash',
      voiceId: 'junho',
      voiceShortName: 'ko-KR-Junho:MAI-Voice-2-Flash',
      style: 'determined',
      styleDegree: 0.48,
      rate: '+18%',
      pitch: '-1%',
      structure: 'one-block',
      segments: Object.freeze(['꼬다리 소유권 분쟁 발생!']),
      neutralNoImpersonation: false,
    }),
    approved({
      menuId: 'sandwich',
      tone: 'alert',
      catalogText: '빵은 잡았는데 속은 탈출!',
      spokenText: '빵은 잡았는데 속은 탈출!',
      sourcePreviewPath: 'tmp/narration-preview/remaining-batch-01/sandwich.mp3',
      targetAssetPath: 'src/assets/narration/sandwich-remaining-batch-01.mp3',
      byteLength: 54_720,
      sha256:
        'A2F7BFB4D6EF6AEB4448534E6001D5DE4F432DE2DC1EF4C4BEDEE8DD552D8760',
      mpegFrameCount: 114,
      exactDurationSeconds: 2.736,
      modelId: 'flash',
      model: 'MAI-Voice-2-Flash',
      voiceId: 'junho',
      voiceShortName: 'ko-KR-Junho:MAI-Voice-2-Flash',
      style: 'joyful',
      styleDegree: 0.48,
      rate: '+22%',
      pitch: '-1%',
      structure: 'adjacent-two-block',
      segments: Object.freeze(['빵은 잡았는데 ', '속은 탈출!']),
      neutralNoImpersonation: false,
    }),
    approved({
      menuId: 'korean-toast',
      tone: 'playful',
      catalogText: '한입 먹자마자 등굣길!',
      spokenText: '한입 먹자마자 등굣길!',
      sourcePreviewPath: 'tmp/narration-preview/remaining-batch-01/korean-toast.mp3',
      targetAssetPath: 'src/assets/narration/korean-toast-remaining-batch-01.mp3',
      byteLength: 56_160,
      sha256:
        'A019F0DDEB0A7282419F124042514A17599662CFB691E10465B398BC0CA81DE0',
      mpegFrameCount: 117,
      exactDurationSeconds: 2.808,
      modelId: 'flash',
      model: 'MAI-Voice-2-Flash',
      voiceId: 'haena',
      voiceShortName: 'ko-KR-Haena:MAI-Voice-2-Flash',
      style: 'joyful',
      styleDegree: 0.46,
      rate: '+20%',
      pitch: '-1%',
      structure: 'one-block',
      segments: Object.freeze(['한입 먹자마자 등굣길!']),
      neutralNoImpersonation: false,
    }),
    approved({
      menuId: 'samgyeopsal',
      tone: 'alert',
      catalogText: '누가 고기 굽는 소리를 내었는가!',
      spokenText: '누가 고기 굽는 소리를 내었는가!',
      sourcePreviewPath: 'tmp/narration-preview/remaining-batch-01/samgyeopsal.mp3',
      targetAssetPath: 'src/assets/narration/samgyeopsal-remaining-batch-01.mp3',
      byteLength: 39_360,
      sha256:
        'FAD7E255933AD9BAFA538CD0FB5B35C43C6FAA8288E8E589A2086F090E081E36',
      mpegFrameCount: 82,
      exactDurationSeconds: 1.968,
      modelId: 'mai-voice-2',
      model: 'MAI-Voice-2',
      voiceId: 'junho',
      voiceShortName: 'ko-KR-Junho:MAI-Voice-2',
      style: 'joyful',
      styleDegree: 0.4,
      rate: '+22%',
      pitch: '-1%',
      structure: 'one-block',
      segments: Object.freeze(['누가 고기 굽는 소리를 내었는가!']),
      neutralNoImpersonation: true,
    }),
    approved({
      menuId: 'grilled-galbi',
      tone: 'playful',
      catalogText: '체면 내려놓고 뼈를 들어라!',
      spokenText: '체면 내려놓고 뼈를 들어라!',
      sourcePreviewPath:
        'tmp/narration-preview/remaining-batch-01/grilled-galbi.mp3',
      targetAssetPath:
        'src/assets/narration/grilled-galbi-remaining-batch-01.mp3',
      byteLength: 35_520,
      sha256:
        '88125BF703A2A4E6915ABA848227F2912B3B0EDD0880ED3262F70A964D3F7A92',
      mpegFrameCount: 74,
      exactDurationSeconds: 1.776,
      modelId: 'flash',
      model: 'MAI-Voice-2-Flash',
      voiceId: 'junho',
      voiceShortName: 'ko-KR-Junho:MAI-Voice-2-Flash',
      style: 'determined',
      styleDegree: 0.48,
      rate: '+20%',
      pitch: '-1%',
      structure: 'adjacent-two-block',
      segments: Object.freeze(['체면 내려놓고 ', '뼈를 들어라!']),
      neutralNoImpersonation: false,
    }),
  ])

export const REMAINING_BATCH_01_GROUP_3_WITHHELD_NARRATION_SELECTIONS =
  Object.freeze([
    Object.freeze({
      menuId: 'tteokbokki',
      catalogText: '떡볶이 포획! 쿨피스 지원 요청!',
      sourcePreviewPath: 'tmp/narration-preview/remaining-batch-01/tteokbokki.mp3',
      byteLength: 64_800,
      sha256:
        'E7D000E53D5623674C4D3054CB225DF484728C49EEA192AFA4527E6CCFA611B7',
      mpegFrameCount: 135,
      exactDurationSeconds: 3.24,
      userFeedback: REMAINING_BATCH_01_GROUP_3_APPROVAL_QUOTE,
      approvalState: 'retake-requested-leading-copy-clipped',
      humanApproved: false,
      deploymentStatus: 'withheld-source-not-integrated',
      currentlyDeployed: false,
      runtimeIntegrationAttempted: false,
    }),
    Object.freeze({
      menuId: 'hamburger',
      catalogText: '햄부기! 햄부기! 햄부기!',
      sourcePreviewPath: 'tmp/narration-preview/remaining-batch-01/hamburger.mp3',
      byteLength: 83_520,
      sha256:
        'CB0977A8A37F398974AC49675E944BA3FF25A44252746014467A814F486E7219',
      mpegFrameCount: 174,
      exactDurationSeconds: 4.176,
      userFeedback: REMAINING_BATCH_01_GROUP_3_APPROVAL_QUOTE,
      approvalState: 'retake-requested-faster-repetition',
      humanApproved: false,
      deploymentStatus: 'withheld-source-not-integrated',
      currentlyDeployed: false,
      runtimeIntegrationAttempted: false,
    }),
  ])
